# Generated by Django 5.2.6 on 2025-10-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('Satellite', 'Satellite'), ('Sensor', 'Sensor'), ('Weather Station', 'Weather Station'), ('Historical Data', 'Historical Data')], max_length=50)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('NetCDF', 'NetCDF'), ('Image', 'Image'), ('Other', 'Other')], max_length=20)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('data_source_url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_real_time', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
